# Generated by Django 4.2.16 on 2024-10-31 15:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Country name')),
                ('photo', models.ImageField(upload_to='countries/', verbose_name='Photo')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Hotel name')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
                ('nutrition', models.IntegerField(verbose_name='Nutrition')),
                ('info', models.TextField(verbose_name='Info')),
                ('photo', models.ImageField(upload_to='hotels/', verbose_name='Photo')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.country', verbose_name='Country')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('child', 'Child'), ('adult', 'Adult'), ('senior', 'Senior')], max_length=10, verbose_name='Category')),
                ('price', models.IntegerField(verbose_name='Price')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tour name')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('date', models.DateField(verbose_name='Date')),
                ('photo', models.ImageField(upload_to='media/', verbose_name='Photo')),
                ('people_count', models.IntegerField(verbose_name='People_count')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.country', verbose_name='Country')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.hotel', verbose_name='Hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Review name')),
                ('star', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Star rating')),
                ('description', models.TextField(verbose_name='Description')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tours.review', verbose_name='Review'),
        ),
    ]
