# Generated by Django 4.2.16 on 2024-11-04 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_remove_hotel_review_remove_tour_price_review_hotel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Total Price'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price_per_person',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10, verbose_name='Price per person'),
        ),
        migrations.CreateModel(
            name='BookingPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Number of persons')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_people', to='tours.booking')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.person')),
            ],
        ),
    ]
