# Generated by Django 4.2.16 on 2024-11-04 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_alter_booking_total_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='people_count',
        ),
    ]
