# Generated by Django 4.2.16 on 2024-11-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_remove_booking_people_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='people_count',
            field=models.IntegerField(default=0),
        ),
    ]
