# Generated by Django 4.2.16 on 2024-11-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_booking_people_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='price_per_person',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price per person'),
        ),
    ]
