# Generated by Django 4.2.16 on 2024-11-05 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_alter_tour_price_per_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='people_count',
        ),
    ]
